### ISSUE TITLE
Mistake in problem 1.2.2

### ISSUE THREAD

**Issue by philip-bl** [dzisandy/NLA#1]
The problem says:

>Prove that if $A$ is a strictly regular matrix, then $ A_1 = D - \frac 1a b c^T $ (see lectures for notations) is also strictly regular.

Here are some problems in your solution:
1. In your decomposition of A into two matrices, you must replace -z with z. Otherwise it's incorrect.
2. Your proof says "A is strictly regular, so it has LU-decomposition". You can't use this fact to prove the required theorem. Because the theorem we're trying to prove is actually a part of proof of the fact that if A is strictly regular, then it has LU-decomposition. (see Tyrtyshnikov's textbook)
3. Your proof says "As we can see this representation of matrix A is LU-decomposition". And then you say that U is upper-triangular. This is incorrect. This representation of A is only the first step of LU-decomposition, and U is not upper triangular.

P.S. If you want to contact me in telegram, I am @RoundRobin

**Comment by dzisandy** [comment]
Chill out, It's not a final version anyway. I will check and replace incorrect statements later.
